name: Pipeline Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Analyzing
        run: |
          for file in $(git ls-files '*.py'); do
            pylint --ignore=unit_test.py,integration_test.py,setup.py "$file"
          done

  build:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package creation
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: image-classifier
          path: dist

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image-classifier
          path: dist

      - name: Install whl files
        run: |
          python -m pip install dist/*.whl

      - name: Install dependencies
        run: |
          pip install -r ./tests/test-requirements.txt

      - name: Run unit tests
        run: |
          pytest ./tests/unit_test.py

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image-classifier
          path: dist

      - name: Install whl files
        run: |
          python -m pip install dist/*.whl

      - name: Install dependencies
        run: |
          pip install -r ./tests/test-requirements.txt

      - name: Run integration tests
        run: |
          pytest ./tests/integration_test.py

  acceptance-test:
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image-classifier
          path: dist

      - name: Install whl files
        run: |
          python -m pip install dist/*.whl

      - name: Install dependencies
        run: |
          pip install -r ./tests/test-requirements.txt

      - name: Run acceptance tests
        run: |
          pytest ./tests/acceptance_test.py
